sqsh -D Cubx -S 192.168.111.10 -U sa -C "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';"

sqsh -D Cubx -S 192.168.111.10 -U sa -C "Select MITARBEITER_ID, MITARBEITER_NR, KUERZEL, NAME, VORNAME from ST_MITARBEITER;"

sqsh -D Cubx -S 192.168.111.10 -U sa -C "SELECT TOP 1 * FROM DZ_DATEN WHERE MITARBEITER_ID=16 ORDER BY DZ_DATUM DESC, DZ_BZ DESC;"

