#!/bin/bash
# inspired by:  http://jimmyg.org/blog/2010/python-daemon-init-script.html

DAEMON=/usr/bin/python
ARGS="/usr/bin/rfidtime serve"
PIDFILE=/var/rfidtime.pid

case "$1" in
  start)

    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user www-data --group www-data \
        -b --make-pidfile \
        --chuid www-data \
        --exec $DAEMON $ARGS
    ;;
  stop)
    echo "Stopping server"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  *)
    echo "Usage: /etc/init.d/rfidtime {start|stop}"
    exit 1
    ;;
esac

exit 0
